### PR TITLE
Adding uni leipzig and refactoring to make adding new cities easier

### PR DESCRIPTION
**Pull request by BaerLKR**
Hey, I hope these changes are in the same direction where you want to see this project go (i moved the urls out of the inputs, maybe not the best semantic choice but like that you only have to edit the flake in one place to add a uni).
Also I added the uni leipzig (didn't see the other PR before)
Thanks for the project, it helped me a lot

### CODE REVIEW

**Comment by MayNiklas** [comment]
Think you for the PR!
I'm going to take a look at it in the following days - I'm currently very busy

**Comment by MayNiklas** [comment]
I see what you're trying to achieve and I like it!

Unfortunately, it won't be as easy as this:
`python3 <url>` won't work! We need to fetch the file in advance.

2 options:

1. we prefetch it using Nix (we then would need the sha)
2. we fetch it using curl

What do you think?

**Comment by MayNiklas** [comment]
I committed a suggestion using wget to fetch the script during runtime, what do you think?

**Comment by MayNiklas** [comment]
We still should update the README 🤔

**Comment by BaerLKR** [comment]
> I see what you're trying to achieve and I like it!
> 
> Unfortunately, it won't be as easy as this: `python3 <url>` won't work! We need to fetch the file in advance.
> 
> 2 options:
> 
>     1. we prefetch it using Nix (we then would need the sha)
> 
>     2. we fetch it using curl
> 
> 
> What do you think?

hey, 
how silly of me, but that should be an easy fix

**Comment by BaerLKR** [comment]
> We still should update the README 🤔

I will quickly make a commit

thanks for the feedback

**Comment by MayNiklas** [comment]
> > We still should update the README 🤔
> 
> I will quickly make a commit
> 
> thanks for the feedback

You don't have to do if you don't want to - I can also update the README later.
Thank you for the suggestions!

One aspect we have to keep in mind:
we are now executing a script without prefetching / hashing it.
-> it's hard to verify, what we are executing in advance 🤔
Still: since the README explains how to install eduroam without this flake, I'm fine with it.

**Comment by BaerLKR** [comment]
maybe it is possible to do a similar thing that I did with the outputs, as in constructing a output for each generated derivation, for the inputs? I don't know, I never tried anything with the inputs
then we could generate the inputs list from the uni list and still prefetch and hash the python scripts

**Comment by MayNiklas** [comment]
> maybe it is possible to do a similar thing that I did with the outputs, as in constructing a output for each generated derivation, for the inputs? I don't know, I never tried anything with the inputs then we could generate the inputs list from the uni list and still prefetch and hash the python scripts

Could be easily done using pkgs.fetchurl.
I'm going to commit an example later for you to look at :)
-> can be easily reverted

**Comment by BaerLKR** [comment]
that would be cool
I tried this 
```nix
    builtins.listToAttrs (builtins.map (e: {
        name = e.name;
        value = {
          flake = false;
          url = "https://cat.eduroam.org/user/API.php?action=downloadInstaller&lang=en&profile=${builtins.toString e.id}&device=linux&generatedfor=user&openroaming=0";
        };
      })
      unis)
    // {
      nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    };
```
to mimic what I did with the outputs but because of lazy evaluation (i think) it is still a `thunk` and not a `set`, even tho is should be one and is one in the repl

edit: 
unis is a variable to the inputs in this case

**Comment by MayNiklas** [comment]
@BaerLKR what do you think about doing it like this?
Hashes are easy to generate (if not set, hash will appear in the error message).

I also will write a CI action to update those hashes in case they change.

**Comment by BaerLKR** [comment]
with the CI integration this seems like a really neat way!

**Review by MayNiklas — APPROVED** [review]

**Pull request merged**
